USE sakila;

-- 1. List the number of films per category.
SELECT 
    c.category_id, 
    COUNT(f.film_id) AS film_count
FROM sakila.film_category AS c
JOIN sakila.film AS f
ON c.film_id = f.film_id
GROUP BY c.category_id;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT 
	s.store_id,
    c.city,
    ct.country
FROM sakila.store as s
JOIN sakila.address as a
ON a.address_id = a.address_id
JOIN sakila.city as c
ON a.city_id = c.city_id
JOIN sakila.country as ct
ON c.country_id = ct.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT 
	s.store_id,
    SUM(p.amount) as "Revenue"
FROM sakila.store as s
JOIN sakila.address as a
ON a.address_id = a.address_id
JOIN sakila.city as c
ON a.city_id = c.city_id
JOIN sakila.country as ct
ON c.country_id = ct.country_id
JOIN sakila.staff as st
ON st.store_id = s.store_id
JOIN sakila.payment as p
ON p.staff_id = st.staff_id
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category.
SELECT 
	c.category_id,
    avg(f.length) as "Average Run Time"
FROM sakila.film_category as c
JOIN sakila.film as f
ON c.film_id = f.film_id
GROUP BY c.category_id;

